let user=null,profile=null,plan=null,recovery=null,weightChart=null;
// Explicit DOM bindings: do not rely on browser-created global IDs.
const $ = (id) => document.getElementById(id);
const auth = $('auth'), app = $('app'), nav = $('nav'), logout = $('logout');
const email = $('email'), password = $('password'), authMsg = $('authMsg');


const key=k=>`fp11:${user?.id||'local'}:${k}`;
const ls=(k,v)=>localStorage.setItem(key(k),JSON.stringify(v));
const lg=k=>{try{return JSON.parse(localStorage.getItem(key(k)))}catch{return null}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const dow=()=>((new Date().getDay()+6)%7);
const goalText=g=>({muscle:'Kas kazanımı',fat:'Yağ kaybı',recomp:'Recomp',strength:'Güç',fitness:'Fitness',performance:'Performans'}[g]||g);
const levelText=x=>({beginner:'Acemi',novice:'Başlangıç',intermediate:'Orta',advanced:'İleri',athlete:'Sporcu/Pro'}[x]||x);

async function init(){
  document.body.classList.toggle('light',localStorage.getItem('fp11theme')==='light');
  if(!window.supabase||!sb){showAuth();if(authMsg)authMsg.textContent='Supabase bağlantısı yüklenemedi. Sayfayı yenile ve internet/CDN erişimini kontrol et.';return;}
  const {data,error}=await sb.auth.getSession();
  if(error) console.error(error);
  user=data?.session?.user||null;
  if(user){showApp();await load();}else showAuth();
  sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user){showApp();setTimeout(()=>load(),0)}else showAuth()});
}
function showAuth(){if(auth)auth.style.display='block';if(app)app.style.display='none';if(nav)nav.style.display='none';if(logout)logout.style.display='none'}
function showApp(){if(auth)auth.style.display='none';if(app)app.style.display='block';if(nav)nav.style.display='flex';if(logout)logout.style.display='block'}
async function signIn(){const em=email.value.trim(),pw=password.value;if(!em||!pw){authMsg.textContent='E-posta ve şifre gerekli.';return}authMsg.textContent='Giriş yapılıyor…';const {error}=await sb.auth.signInWithPassword({email:em,password:pw});authMsg.textContent=error?friendlyAuth(error):'Giriş başarılı.'}
async function signUp(){const em=email.value.trim(),pw=password.value;if(!em||pw.length<6){authMsg.textContent='Geçerli e-posta ve en az 6 karakter şifre gir.';return}authMsg.textContent='Kayıt oluşturuluyor…';const {data,error}=await sb.auth.signUp({email:em,password:pw});if(error){authMsg.textContent=friendlyAuth(error);return}authMsg.textContent=data.session?'Kayıt ve giriş başarılı.':'Kayıt oluşturuldu. E-posta doğrulamasını tamamlayıp giriş yap.'}
function friendlyAuth(e){const m=e?.message||String(e);if(/Invalid login credentials/i.test(m))return'Giriş bilgileri hatalı veya e-posta doğrulanmamış.';if(/Email not confirmed/i.test(m))return'E-posta doğrulanmamış. Gelen doğrulama bağlantısını aç.';if(/already registered/i.test(m))return'Bu e-posta zaten kayıtlı. Giriş yapmayı dene.';return m}
async function signOut(){await sb.auth.signOut()}
function toggleTheme(){const l=!document.body.classList.contains('light');document.body.classList.toggle('light',l);localStorage.setItem('fp11theme',l?'light':'dark')}
function tab(id,b){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active');else{const map={home:0,nutrition:1,progress:2,recovery:3,coach:4,profile:5};document.querySelectorAll('.nav button')[map[id]]?.classList.add('active')}if(id==='progress')renderProgress();if(id==='nutrition')loadFoodHistory();if(id==='recovery')renderRecoveryHistory()}

function normalizeProfile(p){const days=Math.max(2,Math.min(6,+(p?.daysPerWeek??p?.days_per_week??3)));return {id:p?.id||user?.id,fullName:p?.fullName??p?.full_name??'',age:p?.age??null,sex:p?.sex||'male',heightCm:p?.heightCm??p?.height_cm??null,weightKg:p?.weightKg??p?.weight_kg??null,goal:p?.goal||'muscle',level:p?.level||'beginner',daysPerWeek:days,weekdays:normalizeWeekdays(p?.weekdays,days),equipment:p?.equipment||'gym',sessionMinutes:+(p?.sessionMinutes??p?.session_minutes??60),activity:p?.activity||'moderate'}}
function isProfileComplete(p){return !!p&&String(p.fullName||'').trim().length>=2&&Number(p.age)>=13&&Number(p.heightCm)>0&&Number(p.weightKg)>0}

async function load(){try{
  const local=lg('profile');const q=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(q.error)throw q.error;
  profile=normalizeProfile(q.data||local||{id:user.id});
  if(!isProfileComplete(profile)){openProfileSetup();return}
  plan=buildPlan(profile);ls('profile',profile);ls('plan',plan);await loadRecovery();fillProfile();await renderAll();
}catch(e){console.error(e);showApp();authMsg.textContent='Profil/program yüklenemedi: '+(e.message||e)}}

async function loadRecovery(){const {data,error}=await sb.from('recovery_logs').select('*').eq('user_id',user.id).eq('logged_at',today()).maybeSingle();if(error)console.warn(error);recovery=data||lg('recovery');if(recovery)ls('recovery',recovery)}
function calcReadiness(r){if(!r)return null;const sleep=Math.max(0,Math.min(10,+r.sleep_hours||0)),en=Math.max(1,Math.min(10,+r.energy||5)),sor=Math.max(1,Math.min(10,+r.soreness||5)),stress=Math.max(1,Math.min(10,+r.stress||5));return +Math.max(0,Math.min(10,sleep/10*3.2+en/10*3+((10-sor)/10)*2+((10-stress)/10)*1.8)).toFixed(1)}
function coachDecision(){const r=calcReadiness(recovery);if(r===null)return['Recovery gir','Bugün uyku, enerji, soreness ve stresini kaydet.'];if(r<5)return['Koruyucu gün','Yükü yaklaşık %5–10 azalt; failure yapma; RIR 3–4.'];if(r<7)return['Kontrollü ilerle','Planı uygula; RIR 2–3 bırak ve teknik kaliteyi önceliklendir.'];return['İlerleme fırsatı','Tekrar aralığının üst sınırına ulaşırsan küçük bir yük artışı dene.']}
function splitToday(){return splitForToday(plan)}
async function renderAll(){if(!profile||!plan)return;const split=splitToday();todayTitle.textContent=split?`${split} • ${goalText(profile.goal)}`:'Bugün recovery günü';todayTip.textContent=`${profile.fullName||'Sporcu'} • ${profile.daysPerWeek} gün • ${profile.sessionMinutes} dk • ${levelText(profile.level)}`;const [a,b]=coachDecision();decision.innerHTML=`<b>${a}</b><p class="muted" style="margin:6px 0 0">${b}</p>`;readiness.textContent=calcReadiness(recovery)??'—';await renderWorkout(split||'Dinlenme / Recovery');await renderNutrition();renderSchedule()}

function renderSchedule(){const box=document.getElementById('schedule');if(!box||!plan)return;box.innerHTML='<div class="schedule-grid">'+DAYS.map((d,i)=>{const idx=plan.weekdays.indexOf(i),active=idx>=0,name=active?plan.splits[idx%plan.splits.length]:'Dinlenme';return `<div class="item"><b>${d}</b><div class="${active?'ok':'muted'}">${active?'🏋️ '+esc(name):'😴 Dinlenme'}</div>${active?`<div class="small muted">${exercisesFor(name,profile).length} hareket</div><button class="btn secondary small" style="margin-top:6px;width:100%" onclick="showScheduledWorkout(${idx})">Görüntüle</button>`:''}</div>`}).join('')+'</div>'}
async function showScheduledWorkout(idx){if(!plan||idx<0||idx>=plan.splits.length)return;const split=plan.splits[idx];todayTitle.textContent=`${split} • ${goalText(profile.goal)}`;todayTip.textContent=`Programdaki ${idx+1}. antrenman • ${profile.sessionMinutes} dk`;await renderWorkout(split);document.getElementById('workout')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function previous(ex){const {data,error}=await sb.from('workout_sets').select('weight_kg,reps,rir,completed,created_at').eq('user_id',user.id).eq('exercise_id',ex.id).eq('completed',true).order('created_at',{ascending:false}).limit(3);if(error)console.warn(error);return data||[]}
async function renderWorkout(split){const box=document.getElementById('workout');if(!box)return;if(split==='Dinlenme / Recovery'){const next=plan.splits.find(x=>x);box.innerHTML=`<div class="card"><b>🛌 Recovery günü</b><p class="muted">Bugün dinlenme günü. Yine de bir sonraki antrenmanı önceden inceleyebilirsin.</p><button class="btn secondary" onclick="showScheduledWorkout(0)">🏋️ ${esc(next)} egzersizlerini gör</button></div>`;return}const exs=exercisesFor(split,profile);if(!exs.length){box.innerHTML='<div class="card"><b>Egzersiz bulunamadı.</b><p class="muted">Ekipman filtresini kontrol et veya programı yeniden oluştur.</p></div>';return}let html=`<div class="card"><div class="row between"><b>${esc(split)}</b><span class="pill">${exs.length} hareket</span></div>`;for(const e of exs){const prev=await previous(e),pv=prev[0]?`Son: ${prev[0].weight_kg||0} kg × ${prev[0].reps||0} • RIR ${prev[0].rir??'—'}`:'İlk kayıt';html+=`<div class="exercise"><div class="row between"><div class="row"><div>${e.gif?`<img class="ex-gif" src="${e.gif}" alt="${esc(e.name)} hareket animasyonu" loading="lazy" onerror="this.style.display='none'">`:''}</div><div><b>${esc(e.name)}</b><div class="small muted">${esc(e.muscle)} • ${e.min}-${e.max} tekrar • ${e.rest}s • ${pv}</div><div class="small" style="margin-top:6px">💡 ${esc(e.recommendation)}</div></div></div><div class="row"><button class="btn secondary" onclick="showExerciseInfo('${e.id}')">📖 Nasıl yapılır?</button><button class="btn secondary" onclick="startRest(${e.rest})">⏱</button></div></div><div class="set"><span>#</span><span>KG</span><span>REP</span><span>RIR</span><span></span></div>`;for(let s=0;s<e.sets;s++)html+=`<div class="set"><span>${s+1}</span><input class="kg" data-ex="${e.id}" data-set="${s}" type="number" step=".5" placeholder="kg"><input class="rep" data-ex="${e.id}" data-set="${s}" type="number" min="1" placeholder="${Math.round((e.min+e.max)/2)}"><input class="rir" data-ex="${e.id}" data-set="${s}" type="number" min="0" max="5" value="2"><button class="done off" onclick="completeSet(this)">✓</button></div>`;html+='</div>'}html+='<button class="btn primary" style="width:100%" onclick="finishWorkout()">🏁 Antrenmanı Tamamla</button></div>';box.innerHTML=html}
function completeSet(b){b.classList.toggle('off');b.dataset.done=b.classList.contains('off')?'0':'1';b.textContent=b.dataset.done==='1'?'✓ Tamam':'✓'}
let timer=null;
function showExerciseInfo(id){const e=exercisesFor('Full Body',profile).find(x=>x.id===id)||EXERCISES.find(x=>x[0]===id);if(!e)return;const modal=document.getElementById('exerciseModal'),title=document.getElementById('exerciseModalTitle'),body=document.getElementById('exerciseModalBody');title.textContent=e.name;const alts=(typeof exerciseAlternatives==='function'?exerciseAlternatives(e,profile):[]);body.innerHTML=`<div class="ex-detail">${e.gif?`<img src="${e.gif}" alt="${esc(e.name)}" onerror="this.outerHTML='<div class=\"item\">GIF yüklenemedi. Aşağıdaki teknik adımları kullan.</div>'">`:`<div class="item">🎯 Görsel bulunamadı; teknik anlatım aşağıda.</div>`}<div><div class="pill">${esc(e.muscle)} • ${esc(e.equipment)}</div><h3>Nasıl yapılır?</h3><p>${esc(e.instructions)}</p><h3>⚠️ Sık hatalar</h3><p>${esc(e.mistakes)}</p><h3>💡 FitPro önerisi</h3><p>${esc(e.tip)}</p><p><b>${esc(e.recommendation)}</b></p><h3>🔁 Alternatifler</h3><p>${alts.length?alts.map(esc).join(' • '):'Profil ekipmanına uygun alternatif bulunamadı.'}</p></div></div>`;modal.classList.add('show')}
function closeExerciseInfo(){document.getElementById('exerciseModal')?.classList.remove('show')}

function startRest(s){clearInterval(timer);let end=Date.now()+s*1000;timer=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));document.title=`⏱ ${left}s • FitPro`;if(!left){clearInterval(timer);document.title='FitPro ELITE V11';alert('Dinlenme bitti.')}},250)}

async function finishWorkout(){const rows=[...document.querySelectorAll('#workout .set')].filter(r=>r.querySelector('.done')?.dataset.done==='1'&&r.querySelector('.kg')&&r.querySelector('.rep'));if(!rows.length){alert('En az bir seti tamamla.');return}const split=splitToday()||plan.splits[0];const sets=rows.map(r=>({exercise_id:r.querySelector('.kg').dataset.ex,weight_kg:+r.querySelector('.kg').value||0,reps:+r.querySelector('.rep').value||0,rir:+r.querySelector('.rir').value||0,set_number:+r.querySelector('.kg').dataset.set+1})).filter(x=>x.reps>0);if(!sets.length){alert('Tamamlanan setlerde tekrar gir.');return}const {data:w,error}=await sb.from('workouts').insert({user_id:user.id,workout_date:today(),name:split,status:'completed'}).select().single();if(error){alert('Antrenman kaydedilemedi: '+error.message);return}const {error:se}=await sb.from('workout_sets').insert(sets.map(s=>({...s,user_id:user.id,workout_id:w.id,completed:true,is_warmup:false})));if(se){await sb.from('workouts').delete().eq('id',w.id);alert('Setler kaydedilemedi: '+se.message);return}for(const s of sets){if(!s.weight_kg)continue;const e1=s.weight_kg*(1+s.reps/30),oldQ=await sb.from('personal_records').select('value').eq('user_id',user.id).eq('exercise_id',s.exercise_id).eq('record_type','e1rm').maybeSingle(),old=oldQ.data;if(!old||e1>+old.value)await sb.from('personal_records').upsert({user_id:user.id,exercise_id:s.exercise_id,record_type:'e1rm',value:e1,achieved_at:new Date().toISOString()},{onConflict:'user_id,exercise_id,record_type'})}if(window.confetti)confetti({particleCount:90,spread:70});alert('Antrenman kaydedildi. Güzel iş!');await renderProgress()}

function calcTargets(){const w=+profile.weightKg||70,h=+profile.heightCm||175,age=+profile.age||30,sex=profile.sex||'male';let bmr=10*w+6.25*h-5*age+(sex==='female'?-161:5);const act={low:1.35,moderate:1.55,high:1.75}[profile.activity]||1.55,adj={fat:-350,muscle:250,recomp:0,strength:150,fitness:0,performance:200}[profile.goal]||0,kcal=Math.round(bmr*act+adj),protein=Math.round(w*({fat:2,muscle:1.8,recomp:2,strength:1.8,fitness:1.6,performance:1.8}[profile.goal]||1.7)),fat=Math.round(w*.8),carbs=Math.max(0,Math.round((kcal-protein*4-fat*9)/4));return{kcal,protein,carbs,fat}}
async function renderNutrition(){if(!profile)return;const t=calcTargets();macros.innerHTML=`<div class="grid g4"><div class="stat"><span class="muted">Kalori</span><strong>${t.kcal}</strong></div><div class="stat"><span class="muted">Protein</span><strong>${t.protein}g</strong></div><div class="stat"><span class="muted">Karbonhidrat</span><strong>${t.carbs}g</strong></div><div class="stat"><span class="muted">Yağ</span><strong>${t.fat}g</strong></div></div><p class="muted small">Başlangıç tahmini. Kilo trendine göre düzenli ayarlanmalıdır.</p>`;const w=+profile.weightKg||70,water=lg('water')||0;waterTxt.textContent=water+' ml';waterGoal.textContent=Math.round(w*35);waterBar.style.width=Math.min(100,water/(w*35)*100)+'%';const [{data},{data:foods}]=await Promise.all([sb.from('nutrition_logs').select('*').eq('user_id',user.id).eq('logged_at',today()).maybeSingle(),sb.from('food_logs').select('calories').eq('user_id',user.id).eq('logged_at',today())]);todayKcal.textContent=Math.round((+data?.calories||0)+(foods||[]).reduce((a,x)=>a+(+x.calories||0),0))}
function addWater(n){ls('water',(lg('water')||0)+n);renderNutrition()}
async function saveRecovery(){const r={user_id:user.id,logged_at:today(),sleep_hours:+sleep.value||0,energy:+energy.value||5,soreness:+soreness.value||5,stress:+stress.value||5};const {error}=await sb.from('recovery_logs').upsert(r,{onConflict:'user_id,logged_at'});if(error){alert(error.message);return}recovery=r;ls('recovery',r);recoveryResult.innerHTML=`Hazırlık skoru: <b>${calcReadiness(r)}/10</b>`;await renderAll();renderRecoveryHistory()}
async function renderRecoveryHistory(){if(!user)return;const {data}=await sb.from('recovery_logs').select('*').eq('user_id',user.id).order('logged_at',{ascending:false}).limit(14);recoveryHistory.innerHTML=(data||[]).map(r=>`<div class="item"><b>${r.logged_at}</b> • Hazırlık <b>${calcReadiness(r)}/10</b><br><span class="muted">Uyku ${r.sleep_hours}h • Enerji ${r.energy} • Soreness ${r.soreness} • Stres ${r.stress}</span></div>`).join('')||'<div class="muted">Kayıt yok.</div>'}
async function saveNutrition(){const r={user_id:user.id,logged_at:today(),calories:+calories.value||0,protein_g:+protein.value||0,carbs_g:+carbs.value||0,fat_g:+fat.value||0,notes:foodNote.value||''};const {error}=await sb.from('nutrition_logs').upsert(r,{onConflict:'user_id,logged_at'});if(error)alert(error.message);else{alert('Beslenme kaydedildi.');await renderNutrition()}}
async function renderProgress(){if(!user)return;const [{data:ws},{data:sets},{data:prsD},{data:meas}]=await Promise.all([sb.from('workouts').select('id,workout_date').eq('user_id',user.id),sb.from('workout_sets').select('weight_kg,reps,exercise_id').eq('user_id',user.id).eq('completed',true),sb.from('personal_records').select('*').eq('user_id',user.id).order('value',{ascending:false}).limit(20),sb.from('body_measurements').select('measured_at,weight_kg').eq('user_id',user.id).order('measured_at',{ascending:true})]);totalWorkouts.textContent=ws?.length||0;prCount.textContent=prsD?.length||0;const vol=(sets||[]).reduce((a,s)=>a+(+s.weight_kg||0)*(+s.reps||0),0);totalVolume.textContent=Math.round(vol).toLocaleString('tr-TR');weekSets.textContent=(sets||[]).length;weekVol.textContent=Math.round(vol).toLocaleString('tr-TR');lastWeight.textContent=meas?.length?`${meas.at(-1).weight_kg||'—'} kg`:'—';prs.innerHTML=(prsD||[]).map(p=>`<div class="item"><b>${esc(p.exercise_id)}</b><br><span class="muted">e1RM ${(+p.value).toFixed(1)} kg</span></div>`).join('')||'<div class="muted">Henüz PR yok.</div>';if(weightChart)weightChart.destroy();const canvas=document.getElementById('weightChart');if(canvas&&window.Chart)weightChart=new Chart(canvas,{type:'line',data:{labels:(meas||[]).map(x=>x.measured_at),datasets:[{label:'Kilo',data:(meas||[]).map(x=>x.weight_kg),tension:.25}]},options:{responsive:true,plugins:{legend:{display:false}}}})}
async function saveMeasurements(){const r={user_id:user.id,measured_at:today(),weight_kg:+mWeight.value||null,waist_cm:+mWaist.value||null,chest_cm:+mChest.value||null,body_fat_pct:+mBodyFat.value||null};const {error}=await sb.from('body_measurements').insert(r);if(error)alert(error.message);else{if(r.weight_kg){profile.weightKg=r.weight_kg;ls('profile',profile)}alert('Ölçüm kaydedildi.');await renderAll();renderProgress()}}
function fillProfile(){pName.value=profile.fullName||'';pAge.value=profile.age||'';if(document.getElementById('pSex'))pSex.value=profile.sex||'male';pHeight.value=profile.heightCm||'';pWeight.value=profile.weightKg||'';pGoal.value=profile.goal||'muscle';pLevel.value=profile.level||'beginner';pDays.value=profile.daysPerWeek||3;pMinutes.value=profile.sessionMinutes||60;pEquipment.value=profile.equipment||'gym';pActivity.value=profile.activity||'moderate';const selected=normalizeWeekdays(plan?.weekdays??profile.weekdays,profile.daysPerWeek);daysGrid.innerHTML=DAYS.map((d,i)=>`<label>${d}<input type="checkbox" value="${i}" ${selected.includes(i)?'checked':''}></label>`).join('')}
function openProfileSetup(){tab('profile');profile=normalizeProfile({id:user.id,fullName:'',age:null,sex:'male',heightCm:null,weightKg:null,daysPerWeek:3,weekdays:defaultWeekdays(3),goal:'muscle',level:'beginner',equipment:'gym',sessionMinutes:60,activity:'moderate'});plan=buildPlan(profile);fillProfile();const note=document.getElementById('profileNotice');if(note)note.textContent='Profilini tamamla. Günleri seç ve kaydet; program ve egzersizler otomatik oluşacak.'}
function syncDayChecks(){const days=Math.max(2,Math.min(6,+pDays.value||3)),boxes=[...document.querySelectorAll('#daysGrid input[type=checkbox]')],checked=boxes.filter(x=>x.checked);if(checked.length>days)checked.slice(days).forEach(x=>x.checked=false);else if(checked.length<days)boxes.filter(x=>!x.checked).slice(0,days-checked.length).forEach(x=>x.checked=true)}
async function saveProfile(){const days=Math.max(2,Math.min(6,+pDays.value||3));let weekdays=[...document.querySelectorAll('#daysGrid input[type=checkbox]:checked')].map(x=>+x.value);if(weekdays.length!==days)weekdays=normalizeWeekdays(weekdays,days);profile={id:user.id,fullName:pName.value.trim(),age:+pAge.value||null,sex:document.getElementById('pSex')?.value||'male',heightCm:+pHeight.value||null,weightKg:+pWeight.value||null,goal:pGoal.value,level:pLevel.value,daysPerWeek:days,sessionMinutes:+pMinutes.value,equipment:pEquipment.value,activity:pActivity.value,weekdays};if(!isProfileComplete(profile)){alert('Ad, yaş, boy ve kilo alanlarını doldur.');return}const row={id:user.id,full_name:profile.fullName,age:profile.age,sex:profile.sex,height_cm:profile.heightCm,weight_kg:profile.weightKg,goal:profile.goal,level:profile.level,days_per_week:profile.daysPerWeek,weekdays:profile.weekdays,equipment:profile.equipment,session_minutes:profile.sessionMinutes,activity:profile.activity};const {error}=await sb.from('profiles').upsert(row,{onConflict:'id'});if(error){alert('Profil kaydedilemedi: '+error.message);return}ls('profile',profile);plan=buildPlan(profile);ls('plan',plan);await renderAll();alert('Profil ve program hazır.');tab('home')}
async function askAI(q){q=q||aiQuestion.value.trim();if(!q)return;aiAnswer.textContent='AI Coach düşünüyor…';try{const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Oturum bulunamadı');const res=await fetch(`${SUPABASE_URL}/functions/v1/fitpro-coach`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({question:q,profile,plan,recovery,performance:{readiness:calcReadiness(recovery)}})});const j=await res.json();if(!res.ok)throw new Error(j.error||'AI servisi hata verdi');aiAnswer.textContent=j.answer||'Yanıt alınamadı.'}catch(e){aiAnswer.textContent='AI Coach bağlantısı kurulamadı: '+e.message}}
document.addEventListener('change',e=>{if(e.target?.id==='pDays')syncDayChecks()});
// Make inline HTML buttons reliable even if the browser does not expose function declarations globally.
Object.assign(window,{signIn,signUp,signOut,openProfileSetup,saveProfile,tab,toggleTheme});

function authDiagnostics(){
  if(!window.supabase){
    if(authMsg) authMsg.textContent='Supabase kütüphanesi yüklenemedi. İnternet bağlantısını ve CDN erişimini kontrol et.';
    return false;
  }
  if(!sb){
    if(authMsg) authMsg.textContent='Supabase istemcisi başlatılamadı.';
    return false;
  }
  return true;
}

window.addEventListener('DOMContentLoaded',()=>{
  if(email) email.addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});
  if(password) password.addEventListener('keydown',e=>{if(e.key==='Enter')signIn()});
  init();
});
