(function(){'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const sup=()=>window.supabaseClient, uid=()=>window.currentUser?.id;
const labels={beginner:'Başlangıç',intermediate:'Orta',advanced:'İleri',athlete:'Sporcu'}, goals={muscle_gain:'Kas kazanımı',fat_loss:'Yağ kaybı',recomp:'Recomp',strength:'Güç',conditioning:'Kondisyon',sport:'Spor performansı',health:'Genel sağlık'};
const state={profile:null,week:null};
function styles(){if($('fp-v5-style'))return;const s=document.createElement('style');s.id='fp-v5-style';s.textContent='.fp5-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.fp5-stat{padding:12px;border:1px solid var(--border);background:var(--card-inner);border-radius:13px}.fp5-stat b{display:block;font-size:1.18rem;color:var(--primary)}.fp5-stat span{font-size:.65rem;color:var(--text-muted)}.fp5-row{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 12px;border:1px solid var(--border);background:var(--input-bg);border-radius:11px;font-size:.76rem}.fp5-list{display:flex;flex-direction:column;gap:7px}.fp5-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fp5-actions button{width:100%}.fp5-xp{height:8px;background:var(--border);border-radius:999px;overflow:hidden}.fp5-xp>i{display:block;height:100%;background:linear-gradient(90deg,var(--primary),var(--accent));border-radius:999px}@media(max-width:430px){.fp5-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function since(n){const d=new Date();d.setDate(d.getDate()-n);return d.toISOString()}
async function q(table,select='*',filters=[]){if(!uid()||!sup())return[];let x=sup().from(table).select(select);for(const [k,op,v] of filters){x=op==='eq'?x.eq(k,v):op==='gte'?x.gte(k,v):op==='lte'?x.lte(k,v):x}const {data}=await x;return data||[]}
async function load(){if(!uid())return;const p=await q('profiles','*',[['id','eq',uid()]]);state.profile=p[0]||null;const sets=await q('workout_sets','exercise_id,weight_kg,reps,rir,created_at,completed',[['completed','eq',true],['created_at','gte',since(7)]]);const workouts=await q('workouts','id,started_at,completed_at,total_volume_kg,duration_seconds',[['completed_at','gte',since(7)]]);const prs=await q('personal_records','exercise_id,best_1rm',[['user_id','eq',uid()]]);const a=sets.filter(x=>x.rir!=null).map(x=>+x.rir);state.week={sets,workouts,prs,volume:sets.reduce((z,s)=>z+(+s.weight_kg||0)*(+s.reps||0),0),avgRir:a.length?a.reduce((x,y)=>x+y,0)/a.length:null}}
function adaptive(p){const l=p?.experience_level||'beginner',d=+p?.training_days||3,g=p?.goal||'muscle_gain';const x={beginner:[2,'3-4',90,'Teknik + hareket kalitesi'],intermediate:[3,'2-3',120,'Hacim + progressive overload'],advanced:[3,'1-2',150,'Performans + yorgunluk yönetimi'],athlete:[3,'1-2',180,'Periodization + autoregulation']}[l]||[2,'3-4',90,'Teknik'];const split=d<=3?'Full Body':d===4?'Upper / Lower':d===5?'Upper / Lower + Arms':'Push / Pull / Legs';const phase=(g==='strength'||g==='sport')?(l==='athlete'?'Peak':'Strength Base'):g==='fat_loss'?'Fat Loss':g==='conditioning'?'Conditioning':'Hypertrophy';return {sets:x[0],rir:x[1],rest:x[2],focus:x[3],split,phase}}
function adaptiveCard(){const t=$('tab-profile');if(!t||!state.profile)return;let c=$('fp5-adaptive');if(!c){c=document.createElement('div');c.id='fp5-adaptive';c.className='card';t.appendChild(c)}const p=state.profile,a=adaptive(p);c.innerHTML=`<h2>🧬 Adaptive Athlete Engine</h2><div class="fp5-grid"><div class="fp5-stat"><b>${labels[p.experience_level]||'Başlangıç'}</b><span>SEVİYE</span></div><div class="fp5-stat"><b>${goals[p.goal]||'Kas kazanımı'}</b><span>HEDEF</span></div><div class="fp5-stat"><b>${a.split}</b><span>SPLIT</span></div><div class="fp5-stat"><b>${a.phase}</b><span>FAZ</span></div></div><div class="fp5-list" style="margin-top:10px"><div class="fp5-row"><span>Set</span><b>${a.sets} / hareket</b></div><div class="fp5-row"><span>RIR</span><b>${a.rir}</b></div><div class="fp5-row"><span>Dinlenme</span><b>${a.rest} sn</b></div><div class="fp5-row"><span>Yaklaşım</span><b>${a.focus}</b></div></div>`}
async function weekly(){const t=$('tab-analytics');if(!t||!uid())return;let c=$('fp5-weekly');if(!c){c=document.createElement('div');c.id='fp5-weekly';c.className='card';t.appendChild(c)}await load();const w=state.week||{sets:[],workouts:[],prs:[],volume:0,avgRir:null},xp=w.sets.length*10+w.workouts.length*100+w.prs.length*250,lvl=Math.floor(xp/500)+1,need=+state.profile?.training_days||3,adh=Math.min(100,Math.round(w.workouts.length/Math.max(1,need)*100));c.innerHTML=`<h2>📋 Haftalık Sporcu Raporu</h2><div class="fp5-grid"><div class="fp5-stat"><b>${w.workouts.length}</b><span>ANTRENMAN</span></div><div class="fp5-stat"><b>${Math.round(w.volume)} kg</b><span>TONAJ</span></div><div class="fp5-stat"><b>${w.avgRir==null?'—':w.avgRir.toFixed(1)}</b><span>ORT. RIR</span></div><div class="fp5-stat"><b>${adh}%</b><span>UYUM</span></div></div><div style="margin-top:12px;font-size:.7rem"><b>Seviye ${lvl}</b><span style="float:right">${xp%500}/500 XP</span><div class="fp5-xp" style="margin-top:5px"><i style="width:${(xp%500)/5}%"></i></div></div><p style="font-size:.7rem;color:var(--text-muted)">Coach Engine recovery, RIR, hacim, PR ve sıklık verilerini birlikte yorumlar.</p>`}
function quick(){const t=$('tab-coach');if(!t)return;let c=$('fp5-quick');if(!c){c=document.createElement('div');c.id='fp5-quick';c.className='card';t.insertBefore(c,t.firstChild)}const ps=['Bugünkü antrenmanımı analiz et','Son haftadaki ilerlememi değerlendir','Gelecek hafta programımı çıkar','Plateau yaşadığım hareketleri bul'];c.innerHTML=`<h2>⚡ Coach Quick Actions</h2><div class="fp5-actions">${ps.map(p=>`<button class="btn btn-accent" onclick="window.fitProAsk(${JSON.stringify(p)})">${esc(p)}</button>`).join('')}</div>`}
async function ai(prompt){if(!uid())return'Önce giriş yapmalısın.';try{const {data,error}=await sup().functions.invoke('fitpro-coach',{body:{message:prompt,profile:state.profile,week:state.week,language:'tr'}});if(!error&&data?.reply)return data.reply}catch(e){console.warn(e)}return `Güvenli AI servisi henüz deploy edilmemiş. Coach Engine verisi: ${labels[state.profile?.experience_level]||'Başlangıç'} seviyesinde, ${goals[state.profile?.goal]||'kas kazanımı'} hedefi; son 7 gün ${state.week?.workouts?.length||0} antrenman, ${Math.round(state.week?.volume||0)} kg hacim.`}
window.fitProAsk=async function(p){const b=$('coach-chat-box');if(!b)return;b.innerHTML+=`<div class="chat-msg user">${esc(p)}</div><div class="chat-msg ai">⏳ Analiz ediliyor...</div>`;b.scrollTop=b.scrollHeight;const r=await ai(p),last=b.querySelector('.chat-msg.ai:last-child');if(last)last.textContent=r;b.scrollTop=b.scrollHeight}
function extraOptions(){const g=$('fp-goal'),l=$('fp-level');if(g&&!g.querySelector('[value="sport"]'))g.insertAdjacentHTML('beforeend','<option value="sport">Spor performansı</option><option value="health">Genel sağlık</option>');if(l&&!l.querySelector('[value="athlete"]'))l.insertAdjacentHTML('beforeend','<option value="athlete">Sporcu / İleri Performans</option>')}
const oldSave=window.fpSaveProfile;if(oldSave)window.fpSaveProfile=async function(){await oldSave();extraOptions();await load();adaptiveCard();weekly()};
const oldFinish=window.finishWorkout;if(oldFinish)window.finishWorkout=async function(){await oldFinish();await weekly()};
document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{styles();extraOptions();await load();adaptiveCard();weekly();quick()},1400));window.fitProV5={refresh:async()=>{await load();adaptiveCard();await weekly()}};
})();
