/* FitPro ELITE v8 - Pro Training / Tracking / Recovery / AI layer */
(function(){
'use strict';
const $=id=>document.getElementById(id);
let V8={user:null,profile:null,plan:null,recovery:null,workoutId:null,sets:[],aiBusy:false};
const dayNames=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];
const goalLabels={muscle:'Kas kazanımı',fat:'Yağ kaybı',recomp:'Recomp',strength:'Güç',fitness:'Genel fitness',performance:'Performans'};
function client(){return window.supabaseClient||(typeof supabaseClient!=='undefined'?supabaseClient:null)}
function getProfile(){try{return JSON.parse(localStorage.getItem('fitpro_v7_profile_'+(V8.user?.id||'guest'))||'null')}catch{return null}}
function setProfile(p){localStorage.setItem('fitpro_v7_profile_'+(V8.user?.id||'guest'),JSON.stringify(p))}
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function num(v,d=0){const n=parseFloat(v);return Number.isFinite(n)?n:d}
function notify(msg){const old=document.querySelector('.fp8-toast');if(old)old.remove();const x=document.createElement('div');x.className='fp8-toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function calc1RM(w,r){return w>0&&r>0?Math.round(w*(1+r/30)*10)/10:0}
function readiness(r){if(!r)return 7;const sleep=Math.min(10,num(r.sleep,8)/8*10),energy=num(r.energy,7),soreness=11-num(r.soreness,3),stress=11-num(r.stress,3);return Math.round((sleep+energy+soreness+stress)/4*10)/10}
function coachDecision(score){if(score<5)return{tone:'danger',title:'Recovery öncelikli',text:'Bugün yükü %5–10 azalt, failure yapma ve ana hareketlerde RIR 3–4 bırak.'};if(score<7)return{tone:'warning',title:'Kontrollü ilerle',text:'Programı uygula ancak son sette failure yerine RIR 2–3 hedefle.'};return{tone:'good',title:'İyi gün — ilerleme fırsatı',text:'Hedef tekrar aralığının üstüne ulaşırsan bir sonraki exposure’da küçük yük artışı uygula.'}}
async function loadRecovery(){const c=client();if(!c||!V8.user)return null;const {data}=await c.from('recovery_logs').select('*').eq('user_id',V8.user.id).order('logged_at',{ascending:false}).limit(1).maybeSingle();V8.recovery=data;return data}
async function saveRecovery(){const c=client();if(!c||!V8.user)return;const payload={user_id:V8.user.id,sleep_hours:num($('fp8-sleep').value,8),energy:num($('fp8-energy').value,7),soreness:num($('fp8-soreness').value,3),stress:num($('fp8-stress').value,3),notes:$('fp8-recovery-note').value||null,logged_at:new Date().toISOString()};const {error}=await c.from('recovery_logs').insert(payload);if(error)return notify('Recovery kaydedilemedi: '+error.message);V8.recovery=payload;renderRecovery();renderCoach();notify('Recovery kaydedildi.');}
function renderRecovery(){const tab=$('tab-workout');if(!tab)return;let box=document.getElementById('fp8-recovery');if(!box){box=document.createElement('div');box.id='fp8-recovery';tab.prepend(box)}const r=V8.recovery||{sleep_hours:8,energy:7,soreness:3,stress:3};const score=readiness({sleep:r.sleep_hours,energy:r.energy,soreness:r.soreness,stress:r.stress});box.innerHTML=`<div class="card"><h2>🧠 Günlük Hazırlık <span class="fp8-score">${score}/10</span></h2><div class="fp8-grid"><label>Uyku (saat)<input id="fp8-sleep" type="number" step="0.1" min="0" max="14" value="${r.sleep_hours}"></label><label>Enerji (1–10)<input id="fp8-energy" type="number" min="1" max="10" value="${r.energy}"></label><label>Kas ağrısı (1–10)<input id="fp8-soreness" type="number" min="1" max="10" value="${r.soreness}"></label><label>Stres (1–10)<input id="fp8-stress" type="number" min="1" max="10" value="${r.stress}"></label></div><input id="fp8-recovery-note" class="fp8-input" placeholder="Bugün nasıl hissediyorsun?"><button class="btn btn-primary" onclick="fp8SaveRecovery()">Recovery Kaydet</button></div>`}
function renderCoach(){const tab=$('tab-workout');if(!tab)return;let box=document.getElementById('fp8-coach');if(!box){box=document.createElement('div');box.id='fp8-coach';tab.insertBefore(box,tab.children[1]||null)}const score=readiness(V8.recovery);const d=coachDecision(score);box.innerHTML=`<div class="coach-card fp8-coach-${d.tone}"><div class="coach-avatar">🧠</div><div><div class="coach-title">FITPRO COACH · ${d.title}</div><div class="coach-text">${d.text}</div><div class="fp8-mini">Hazırlık ${score}/10 · ${V8.profile?escape(goalLabels[V8.profile.goal]||'Fitness'):''}</div></div></div>`}
function currentDay(){if(!V8.plan)return null;const today=(new Date().getDay()+6)%7;let i=V8.plan.weekdays?.indexOf(today);if(i<0)i=0;return V8.plan.days?.[i]||V8.plan.days?.[0]}
async function previousPerformance(exId){const c=client();if(!c||!V8.user)return null;try{const {data}=await c.from('workout_sets').select('weight_kg,reps,rir,created_at,workout_id').eq('user_id',V8.user.id).eq('exercise_id',exId).eq('completed',true).order('created_at',{ascending:false}).limit(12);return data||[]}catch{return[]}}
async function renderWorkoutPro(day){const c=$('workout-list');if(!c||!day)return;const decision=coachDecision(readiness(V8.recovery));c.innerHTML=`<div class="fp8-session-head"><b>${escape(day.label)}</b><span>${day.exercises.length} hareket · ${V8.profile?.sessionMinutes||60} dk</span></div>`;for(let i=0;i<day.exercises.length;i++){const e=day.exercises[i],hist=await previousPerformance(e.id),last=hist?.[0];let target=num(last?.weight_kg,0);if(!target)target=0;const sets=Array.from({length:e.sets},(_,s)=>`<div class="fp8-set"><b>${s+1}</b><input inputmode="decimal" type="number" step="0.5" class="fp8-set-weight" data-ex="${e.id}" data-set="${s}" value="${target||''}" placeholder="kg"><input inputmode="numeric" type="number" class="fp8-set-reps" data-ex="${e.id}" data-set="${s}" value="" placeholder="rep"><input inputmode="numeric" type="number" min="0" max="5" class="fp8-set-rir" data-ex="${e.id}" data-set="${s}" value="${e.rir==='3–4'?3:e.rir==='2–3'?2:1}" placeholder="RIR"><button class="fp8-check" onclick="fp8CompleteSet(this,${e.rest})">✓</button></div>`).join('');c.insertAdjacentHTML('beforeend',`<div class="ex-item fp8-ex"><div class="ex-header"><div class="ex-title">${i+1}. ${escape(e.name)}</div><span>${escape(e.muscle)} · ${escape(e.equipment)}</span></div><div class="ex-guide"><b>Hedef:</b> ${e.sets} set · ${e.reps} · RIR ${e.rir} · ${e.rest} sn dinlenme<br><b>Coach:</b> ${decision.text}</div><div class="fp8-set-head"><span>Set</span><span>KG</span><span>REP</span><span>RIR</span><span></span></div>${sets}<div class="fp8-ex-foot">${last?`Son kayıt: ${last.weight_kg} kg × ${last.reps} · RIR ${last.rir??'-'} · e1RM ${calc1RM(num(last.weight_kg),num(last.reps))} kg`:'İlk kayıt — başlangıç kilonu seç ve ilerlemeyi FitPro takip etsin.'}</div></div>`)}c.insertAdjacentHTML('beforeend',`<button class="btn btn-primary fp8-finish" onclick="fp8FinishWorkout()">🏁 Antrenmanı Bitir ve Kaydet</button>`)}
function fp8CompleteSet(btn,rest){btn.classList.toggle('done');if(btn.classList.contains('done')){try{startTimer(rest)}catch{}}}
async function startWorkout(){const c=client();if(!c||!V8.user){V8.workoutId='local-'+Date.now();return}const d=currentDay();const {data,error}=await c.from('workouts').insert({user_id:V8.user.id,name:d?.label||'Antrenman',started_at:new Date().toISOString(),cycle_day:V8.plan?.weekdays?.[V8.plan.weekdays.indexOf((new Date().getDay()+6)%7)]??0}).select('id').single();if(error){notify('Antrenman başlatılamadı');return}V8.workoutId=data.id;notify('Antrenman başlatıldı.')}
async function fp8FinishWorkout(){if(!V8.workoutId)await startWorkout();const c=client();const rows=[];document.querySelectorAll('.fp8-set').forEach(row=>{const w=num(row.querySelector('.fp8-set-weight')?.value,0),r=num(row.querySelector('.fp8-set-reps')?.value,0),rir=num(row.querySelector('.fp8-set-rir')?.value,2);const ex=row.querySelector('.fp8-set-weight')?.dataset.ex;const done=row.querySelector('.fp8-check')?.classList.contains('done')||r>0;if(done&&ex&&r>0)rows.push({workout_id:V8.workoutId,exercise_id:ex,user_id:V8.user?.id,weight_kg:w,reps:r,rir,completed:true,set_number:rows.filter(x=>x.exercise_id===ex).length+1,is_warmup:false})});if(c&&rows.length){const {error}=await c.from('workout_sets').insert(rows);if(error)notify('Setler kaydedilirken hata: '+error.message);else{await c.from('workouts').update({completed_at:new Date().toISOString(),total_volume_kg:rows.reduce((a,x)=>a+x.weight_kg*x.reps,0)}).eq('id',V8.workoutId);await updatePRs(rows);notify(`${rows.length} set kaydedildi. 🔥`);}}else{localStorage.setItem('fitpro_v8_last_workout',JSON.stringify(rows));notify('Antrenman yerel olarak kaydedildi.')};renderProgress();}
async function updatePRs(rows){const c=client();if(!c||!V8.user)return;for(const x of rows){const best=calc1RM(x.weight_kg,x.reps);const {data}=await c.from('personal_records').select('*').eq('user_id',V8.user.id).eq('exercise_id',x.exercise_id).maybeSingle();if(!data||best>num(data.best_1rm))await c.from('personal_records').upsert({user_id:V8.user.id,exercise_id:x.exercise_id,best_weight_kg:x.weight_kg,best_reps:x.reps,best_1rm:best,updated_at:new Date().toISOString()},{onConflict:'user_id,exercise_id'})}}
async function renderProgress(){const tab=$('tab-progress');if(!tab)return;let box=document.getElementById('fp8-progress');if(!box){box=document.createElement('div');box.id='fp8-progress';tab.prepend(box)}const c=client();let sets=[],prs=[];if(c&&V8.user){try{sets=(await c.from('workout_sets').select('*').eq('user_id',V8.user.id).eq('completed',true).order('created_at',{ascending:false}).limit(500)).data||[];prs=(await c.from('personal_records').select('*').eq('user_id',V8.user.id).order('best_1rm',{ascending:false}).limit(20)).data||[]}catch{}}const vol=sets.reduce((a,x)=>a+num(x.weight_kg)*num(x.reps),0),count=new Set(sets.map(x=>x.workout_id)).size;box.innerHTML=`<div class="card"><h2>📊 Performans Merkezi</h2><div class="fp8-stats"><div><b>${count}</b><small>Antrenman</small></div><div><b>${Math.round(vol).toLocaleString('tr-TR')}</b><small>Toplam kg</small></div><div><b>${prs.length}</b><small>PR</small></div><div><b>${readiness(V8.recovery)}</b><small>Hazırlık</small></div></div><div class="fp8-prs"><b>🏆 En iyi tahmini 1RM</b>${prs.slice(0,8).map(p=>`<div>${escape(p.exercise_id)} <strong>${p.best_1rm} kg</strong></div>`).join('')||'<small>Henüz PR yok.</small>'}</div></div>`}
async function openAI(){const q=prompt('AI Coach\'a ne sormak istiyorsun?');if(!q)return;const c=client();if(!c||!V8.user)return notify('Önce giriş yapmalısın.');V8.aiBusy=true;notify('Coach düşünüyor…');const context={profile:V8.profile,goal:goalLabels[V8.profile?.goal],recovery:V8.recovery,plan:V8.plan?.days?.map(d=>({name:d.label,exercises:d.exercises?.map(e=>({id:e.id,name:e.name,sets:e.sets,reps:e.reps,rir:e.rir}))})),question:q};try{const {data,error}=await c.functions.invoke('fitpro-coach',{body:{question:q,context}});if(error)throw error;alert('🧠 FitPro Coach\n\n'+(data?.answer||'Coach cevap veremedi.'));}catch(e){alert('AI Coach bağlantısı kurulamadı. Supabase Edge Function ve OPENAI_API_KEY ayarlarını kontrol et.\n\n'+e.message)}finally{V8.aiBusy=false}}
function addV8UI(){const st=document.createElement('style');st.textContent=`.fp8-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fp8-grid label{font-size:.72rem;color:var(--text-muted);font-weight:700}.fp8-grid input,.fp8-input{width:100%;margin-top:5px;padding:10px;border-radius:10px;border:1px solid var(--border);background:var(--input-bg);color:var(--text)}.fp8-score{color:var(--primary)}.fp8-coach-danger{border-color:var(--danger)!important}.fp8-coach-warning{border-color:var(--warning)!important}.fp8-coach-good{border-color:var(--primary)!important}.fp8-mini{font-size:.7rem;color:var(--text-muted);margin-top:5px}.fp8-session-head{display:flex;justify-content:space-between;padding:10px 4px;color:var(--text-muted);font-size:.8rem}.fp8-set-head,.fp8-set{display:grid;grid-template-columns:32px 1fr 1fr 1fr 40px;gap:6px;align-items:center}.fp8-set-head{font-size:.65rem;color:var(--text-muted);padding:0 6px 4px}.fp8-set{margin-bottom:6px}.fp8-set input{min-width:0;padding:9px;border-radius:9px;border:1px solid var(--border);background:var(--input-bg);color:var(--text)}.fp8-check{height:36px;border-radius:9px;border:1px solid var(--border);background:var(--card-bg);color:var(--primary);font-weight:900}.fp8-check.done{background:var(--primary);color:#fff}.fp8-ex-foot{font-size:.7rem;color:var(--text-muted);margin-top:8px}.fp8-finish{width:100%;margin-bottom:20px}.fp8-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.fp8-stats>div{background:var(--card-inner);padding:10px;border-radius:12px;text-align:center}.fp8-stats b{display:block;font-size:1.05rem;color:var(--primary)}.fp8-stats small{font-size:.62rem;color:var(--text-muted)}.fp8-prs{margin-top:12px;background:var(--card-inner);padding:12px;border-radius:12px}.fp8-prs div{display:flex;justify-content:space-between;border-bottom:1px solid var(--border);padding:7px 0;font-size:.76rem}.fp8-toast{position:fixed;top:16px;left:50%;transform:translateX(-50%);z-index:30000;background:var(--card-bg);border:1px solid var(--primary);color:var(--text);padding:10px 14px;border-radius:12px;box-shadow:var(--shadow);font-size:.78rem;font-weight:700}.fp8-ai-btn{width:100%;margin-top:8px}.fp8-quick{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}@media(max-width:420px){.fp8-stats{grid-template-columns:1fr 1fr}}`;document.head.appendChild(st)
  const p=$('tab-profile');if(p){const card=document.createElement('div');card.className='card';card.innerHTML=`<h2>🧠 AI Coach</h2><p style="font-size:.78rem;color:var(--text-muted)">Profilin, programın, recovery ve performans verilerinle kişisel koç desteği.</p><button class="btn btn-primary fp8-ai-btn" onclick="fp8AskAI()">🤖 AI Coach'a Sor</button><div class="fp8-quick"><button class="btn btn-accent" onclick="fp8QuickAI('Bugünkü antrenmanımı analiz et.')">Bugünü analiz et</button><button class="btn btn-accent" onclick="fp8QuickAI('Son performansımda neyi geliştirmeliyim?')">Gelişim önerisi</button></div>`;p.appendChild(card)}
}
async function boot(){try{const c=client();if(c){const r=await c.auth.getUser();V8.user=r.data.user}}catch{}V8.profile=getProfile();try{V8.plan=JSON.parse(localStorage.getItem('fitpro_v7_plan_'+(V8.user?.id||'guest'))||'null')}catch{}if(!V8.plan&&window.fpGeneratePlan){try{window.fpGeneratePlan();V8.plan=JSON.parse(localStorage.getItem('fitpro_v7_plan_'+(V8.user?.id||'guest'))||'null')}catch{}}await loadRecovery();addV8UI();renderRecovery();renderCoach();if(window.renderAdaptiveWorkout&&V8.plan){}const d=currentDay();if(d)await renderWorkoutPro(d);await renderProgress();addAIButtonToNav();}
function addAIButtonToNav(){const n=document.getElementById('bottom-nav');if(!n||n.querySelector('.fp8-nav-ai'))return;const b=document.createElement('button');b.className='nav-item fp8-nav-ai';b.innerHTML='<span>🤖</span>Coach';b.onclick=()=>fp8AskAI();n.appendChild(b)}
window.fp8SaveRecovery=saveRecovery;window.fp8CompleteSet=fp8CompleteSet;window.fp8FinishWorkout=fp8FinishWorkout;window.fp8AskAI=openAI;window.fp8QuickAI=q=>{const old=window.prompt;window.prompt=()=>q;openAI().finally(()=>window.prompt=old)};
document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1000));
})();
