(function(){'use strict';
const $=id=>document.getElementById(id);
const DAYS=[['1','Pazartesi'],['2','Salı'],['3','Çarşamba'],['4','Perşembe'],['5','Cuma'],['6','Cumartesi'],['0','Pazar']];
const SPLITS={2:['A — Üst Vücut','B — Alt + Sırt'],3:['A — Full Body','B — Full Body','C — Full Body'],4:['A — Upper','B — Lower','C — Upper','D — Lower'],5:['A — Push','B — Pull','C — Legs','D — Upper','E — Lower'],6:['A — Push','B — Pull','C — Legs','D — Push','E — Pull','F — Legs']};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const sup=()=>window.supabaseClient, uid=()=>window.currentUser?.id;
const state={schedule:[],count:2,aiRecommendation:null};
function styles(){if($('fp-v6-style'))return;const s=document.createElement('style');s.id='fp-v6-style';s.textContent=`
.fp6-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fp6-days{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.fp6-day{padding:9px 5px;border:1px solid var(--border);background:var(--input-bg);border-radius:10px;text-align:center;font-size:.68rem;cursor:pointer}.fp6-day input{display:none}.fp6-day.active{border-color:var(--primary);background:var(--primary-glow);color:var(--primary);font-weight:800}.fp6-badge{display:inline-block;padding:4px 8px;border:1px solid var(--border);border-radius:999px;font-size:.65rem}.fp6-rec{padding:11px;border:1px solid var(--accent);border-radius:12px;background:var(--card-inner);font-size:.74rem;line-height:1.45}.fp6-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:9px 11px;border:1px solid var(--border);background:var(--input-bg);border-radius:10px;font-size:.72rem}@media(max-width:430px){.fp6-days{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(s)}
function today(){return String(new Date().getDay())}
function readSchedule(){try{const x=JSON.parse(localStorage.getItem('fitpro_training_schedule_v6')||'null');if(Array.isArray(x)&&x.length)return x}catch{}return state.schedule.length?state.schedule:['1','4'];}
function saveSchedule(x){state.schedule=x;localStorage.setItem('fitpro_training_schedule_v6',JSON.stringify(x));localStorage.setItem('fitpro_training_days_v6',String(x.length));}
function countRecommendation(){const p=window.fitproV5?.getState?.()?.profile||null;const level=p?.experience_level||'beginner';if(level==='beginner')return 2;if(level==='athlete')return 4;return Math.min(4,Math.max(3,Number(p?.training_days)||3));}
function scheduleCard(){styles();const tab=$('tab-profile');if(!tab)return;let c=$('fp6-schedule');if(!c){c=document.createElement('div');c.id='fp6-schedule';c.className='card';tab.insertBefore(c,tab.firstChild)}const saved=readSchedule();const rec=countRecommendation();c.innerHTML=`<h2>📅 Kişisel Antrenman Takvimi</h2><p style="font-size:.73rem;color:var(--text-muted);margin-bottom:10px">Kaç gün çalışacağını <b>sen seçersin</b>. FitPro, seçtiğin günler arasında programı dağıtır. Yorulduğunda 4 günden 2 güne düşürebilirsin; program yeniden dengelenir.</p><div class="fp6-rec">🤖 <b>Coach önerisi:</b> Şu anki profil verilerine göre <b>${rec} gün</b> sürdürülebilir görünüyor. Bu sadece öneridir; seçimi sen yaparsın.</div><div style="margin-top:11px"><div class="fp6-days">${DAYS.map(([v,n])=>`<label class="fp6-day ${saved.includes(v)?'active':''}"><input type="checkbox" value="${v}" ${saved.includes(v)?'checked':''} onchange="window.fitproSetDay(this)"><span>${n.slice(0,3)}</span></label>`).join('')}</div></div><div style="margin-top:10px"><label style="font-size:.7rem;color:var(--text-muted)">Haftalık antrenman sayısı</label><select id="fp6-count" style="width:100%;margin-top:5px;background:var(--input-bg);color:var(--text);border:1px solid var(--border);padding:10px;border-radius:9px" onchange="window.fitproCountChanged(this.value)">${[2,3,4,5,6].map(n=>`<option value="${n}" ${saved.length===n?'selected':''}>${n} gün</option>`).join('')}</select></div><div id="fp6-plan" style="margin-top:10px"></div><button class="btn btn-primary" style="width:100%;margin-top:10px" onclick="window.fitproSaveSchedule()">💾 Takvimi Kaydet ve Programı Uyarla</button>`;renderPlan();}
function renderPlan(){const c=$('fp6-plan');if(!c)return;const days=readSchedule();const n=days.length;const names=SPLITS[n]||SPLITS[2];c.innerHTML=`<div style="display:flex;flex-direction:column;gap:7px">${days.map((d,i)=>`<div class="fp6-row"><span>${DAYS.find(x=>x[0]===d)?.[1]||d}</span><b>${names[i]||'Antrenman'}</b></div>`).join('')}</div>`}
window.fitproSetDay=function(el){const checked=[...document.querySelectorAll('#fp6-schedule input[type=checkbox]:checked')].map(x=>x.value);if(checked.length>6){el.checked=false;return}state.schedule=checked;document.querySelectorAll('#fp6-schedule .fp6-day').forEach(x=>x.classList.toggle('active',x.querySelector('input').checked));if($('fp6-count'))$('fp6-count').value=checked.length||2;renderPlan()};
window.fitproCountChanged=function(v){let days=readSchedule();const n=Number(v);if(days.length>n)days=days.slice(0,n);while(days.length<n){const next=DAYS.find(x=>!days.includes(x[0]));if(!next)break;days.push(next[0])}saveSchedule(days);scheduleCard()};
window.fitproSaveSchedule=async function(){let days=[...document.querySelectorAll('#fp6-schedule input[type=checkbox]:checked')].map(x=>x.value);if(days.length<2){alert('En az 2 antrenman günü seçmelisin.');return}if(days.length>6){alert('En fazla 6 gün seçebilirsin.');return}saveSchedule(days);try{if(uid()&&sup())await sup().from('profiles').update({training_days:days.length,training_schedule:days}).eq('id',uid())}catch(e){console.warn(e)}applyToday();alert(`Takvim kaydedildi: ${days.length} gün. FitPro programını buna göre dağıtacak.`);};
function applyToday(){const days=readSchedule(),td=today(), idx=days.indexOf(td);const sel=$('manual-day-select');if(!sel)return;if(idx<0){sel.value=days.length>0?'2':'1';}else{const n=idx%2===0?1:3;sel.value=String(n)}if(typeof renderWorkoutList==='function')renderWorkoutList();}
function replaceCycleSelector(){const sel=$('manual-day-select');if(!sel)return;const days=readSchedule(), names=SPLITS[days.length]||SPLITS[2];sel.innerHTML=days.map((d,i)=>`<option value="${i%2===0?1:3}">${DAYS.find(x=>x[0]===d)?.[1]||d} — ${names[i]||'Antrenman'}</option>`).join('');applyToday()}
function adaptiveTrainingCard(){const tab=$('tab-workout');if(!tab)return;let c=$('fp6-adaptive');if(!c){c=document.createElement('div');c.id='fp6-adaptive';c.className='card';const anchor=$('workout-card');tab.insertBefore(c,anchor)}const days=readSchedule();const idx=days.indexOf(today());const active=idx>=0;const p=window.fitproV5?.getState?.()?.profile;const level=p?.experience_level||'beginner';const n=days.length;const intensity=n>=5?'yüksek':n>=4?'orta-yüksek':n===3?'orta':'düşük-orta';c.innerHTML=`<h2>🎯 Bugünkü Plan</h2><div class="fp6-grid"><div class="fp6-badge">${active?'🟢 Antrenman günü':'🔵 Dinlenme günü'}</div><div class="fp6-badge">${n} gün/hafta</div><div class="fp6-badge">${esc(level)}</div><div class="fp6-badge">Yük: ${intensity}</div></div>${!active?'<p style="font-size:.73rem;color:var(--text-muted);margin-top:10px">Bugün planlı dinlenme. Recovery ve mobiliteyi önceliklendir.</p>':''}`}
async function aiScheduleAdvice(){try{const s=window.fitproCoach?.getState?.();const p=window.fitproV5?.getState?.()?.profile;if(!sup()||!uid())return;const {data,error}=await sup().functions.invoke('fitpro-coach',{body:{message:'Kullanıcının seçtiği haftalık antrenman günlerini değerlendir. Eğer sürdürülebilirlik açısından fazla görünüyorsa daha az gün öner; kesinlikle kullanıcının seçimini zorla değiştirme. Kısa ve uygulanabilir Türkçe cevap ver.',profile:p,week:s?.weekly,schedule:readSchedule(),language:'tr'}});if(!error&&data?.reply)state.aiRecommendation=data.reply}catch(e){}}
const oldFinish=window.finishWorkout;if(oldFinish)window.finishWorkout=async function(){await oldFinish();setTimeout(()=>{adaptiveTrainingCard();replaceCycleSelector()},500)};
document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{styles();scheduleCard();replaceCycleSelector();adaptiveTrainingCard();await aiScheduleAdvice()},1600));
window.fitproV6={refresh:()=>{scheduleCard();replaceCycleSelector();adaptiveTrainingCard()},getSchedule:()=>readSchedule()};
})();
